### ISSUE TITLE
Leveldown Install problem!

### ISSUE THREAD

**Issue by GaryGav** [notnotse/ol-couchdb-source#2]
Hi when trying to install ol-couchdb-source I get the following error can anyone she'd some light on this.

[2018-11-16T12_48_18_094Z-debug.txt](https://github.com/notnotse/ol-couchdb-source/files/2589376/2018-11-16T12_48_18_094Z-debug.txt)

Apologies i'm new to node.js :)

> leveldown@4.0.1 install /home/datateam/OpenLayers/new-project/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.1.0 runtime=node arch=x64 platform=linux)
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/datateam/OpenLayers/new-project/node_modules/leveldown/build'
gyp ERR! System Linux 4.15.0-38-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/datateam/OpenLayers/new-project/node_modules/leveldown
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN openlayerscdb@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@4.0.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/datateam/.npm/_logs/2018-11-16T12_48_18_094Z-debug.log

**Comment by bobobobo** [comment]
Hmm, strange... Do you have full access to /home/datateam/OpenLayers/new-project/?

**Comment by GaryGav** [comment]
I managed to get it installed running the command "sudo npm i -g ol-couchdb-source --unsafe-perm=true --allow-root" however I have had the warning below regarding openlayer version. I am currently using version OpenLayers v5.3.0.

"Thank you for using level!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/level/donate

npm WARN ol-couchdb-source@1.3.1 requires a peer of openlayers@^4.x but none is installed. You must install peer dependencies yourself.

+ ol-couchdb-source@1.3.1
added 111 packages from 88 contributors in 23.55s"


> Hmm, strange... Do you have full access to /home/datateam/OpenLayers/new-project/?

**Comment by itjope** [comment]
ol-couchdb-source currently does not support OpenLayers > 5.0.0. 
Issue #3  - Upgrade to OpenLayers 5.x

**Comment by GaryGav** [comment]
Hi, thanks for your response itjope, I have tried installing openlayers version
4.6.5 but it still will not work for me. When I use the example map code on the ol-couchdb-source page i get the following error from openlayers: 
![image](https://user-images.githubusercontent.com/39549757/48916170-27bdbe00-ee79-11e8-845e-5874ddb6f307.png)

I appreciate any help you can give in this matter.

cheers

**Comment by GaryGav** [comment]
I forgot to add a copy of the debug.log [2018-11-22T16_59_00_299Z-debug.log](https://github.com/notnotse/ol-couchdb-source/files/2608928/2018-11-22T16_59_00_299Z-debug.log)

Cheers

**Comment by bobobobo** [comment]
Hi @GaryGav, 

It looks like you misspelled ol-couchdb-source, you missed the last 'e'.

**Comment by bobobobo** [comment]
I see that the example in the readme is wrong, sorry for that! Try changing it to **ol-couchdb-source**

**Comment by GaryGav** [comment]
Hi @bobobobo  thanks for responding again! I am still getting the error even with the correct spelling :( 
I installed openlayers via command "npm i openlayers" rather than "npm i ol" to get an older non 5.x version then followed the instructions on the page below.

https://openlayers.org/en/latest/doc/tutorials/bundle.html

I then installed ol-couchdb-source via "npm i ol-couchdb-source --python=python3.7"

I have attached the complete output from command line from the steps I have taken in case that sheds any light. I'm probably doing something obviously wrong, apologies I am new to all of this.

I appreciate you both having taken the time to respond.

Cheers
[npm output.txt](https://github.com/notnotse/ol-couchdb-source/files/2610179/npm.output.txt)

**Comment by GaryGav** [comment]
Apologies it's actually a different error now that I have corrected the spelling

![image](https://user-images.githubusercontent.com/39549757/48935847-fa1c5780-ef00-11e8-8ffa-a69c402c6979.png)

**Comment by itjope** [comment]
@GaryGav Can you attach your `package.json` file so we can try to reproduce your error.

**Comment by GaryGav** [comment]
Hi itjope, 

I deleted the entire folder and started again and it now seems to be working or at least compiling.

![image](https://user-images.githubusercontent.com/39549757/49008905-f722a080-f166-11e8-90b0-be421a18dd0f.png)

I installed everything as outlined in the attached install log:
[Install log.txt](https://github.com/notnotse/ol-couchdb-source/files/2615059/Install.log.txt)

Basically I am trying to get a basic set up where I can upload geojson GIS data files to a couchdb and then display these overlaid on a basic map that can then be accessed in a browser via openlayers.

I am using the index.html and index.js below:
[indexhtml.txt](https://github.com/notnotse/ol-couchdb-source/files/2615079/indexhtml.txt)

[indexjs.txt](https://github.com/notnotse/ol-couchdb-source/files/2615080/indexjs.txt)

and the example GeoJson file:

[110_lakesjson.txt](https://github.com/notnotse/ol-couchdb-source/files/2615084/110_lakesjson.txt)

The geoJson is a valid geoJson as it can be viewed when dragged onto the drag and drop example on the openlayers page. When I use the setup described above everything seems to compile however I merely get a blank screen on http://localhost:1234/ 


![image](https://user-images.githubusercontent.com/39549757/49009816-6ac5ad00-f169-11e8-907f-276fc779d758.png)


When I use the example index.js on the openlayers page it loads up fine. 

![image](https://user-images.githubusercontent.com/39549757/49009882-90eb4d00-f169-11e8-87ef-2f2c6c50d892.png)

There's probably something very obvious I am missing as I am new to all of this but any help getting the set up described working with your package ol-couchdb-source would be a lifesaver!

This is my package.json also:
[packagejson.txt](https://github.com/notnotse/ol-couchdb-source/files/2615129/packagejson.txt)

Thanks in advance.

Gary
